identifier: k5z5zf21t8k405q0
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: BeemaDukaan
homeFolder: F:\AngularProjects\beemadukaan
distFolder: dist/BeemaDukaan
outDir: F:\AngularProjects\beemadukaan\dist\static
handle404: ''
allowErrorCollect: false
